name: Build and Test on Windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java for Spring Boot backend
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    # Step 3: Build the Spring Boot backend
    - name: Build Backend
      working-directory: demo
      run: mvn clean install

    # Step 4: Test the Spring Boot backend
    - name: Test Backend
      working-directory: demo
      run: mvn test

    # Step 5: Set up Node.js for Vite frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 6: Install dependencies and build the Vite app
    - name: Install and Build Frontend
      working-directory: my-vite-app
      run: |
        npm install
        npm run build
