name: Build and Deploy Docker Image on Approved Pull Request

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:


jobs:
  build-and-deploy:
    if: ${{ github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main' }}
    runs-on: linux-latest


    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java for Spring Boot backend
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the Spring Boot backend (skip tests)
      - name: Build Backend (Skip Tests)
        working-directory: demo
        run: mvn clean install -DskipTests

      # Step 4: Set up Node.js for Vite frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 5: Install dependencies and build the Vite app (skip tests)
      - name: Install and Build Frontend (Skip Tests)
        working-directory: my-vite-app
        run: |
          npm install
          npm run build --if-present --skip-tests

      # Step 6: Log in to Docker Hub (requires Docker Hub credentials stored in secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build Docker image for backend
      - name: Build Docker Image for Backend
        working-directory: demo
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-backend:latest .

      # Step 8: Build Docker image for frontend
      - name: Build Docker Image for Frontend
        working-directory: my-vite-app
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/vite-frontend:latest .

      # Step 9: Push backend Docker image to Docker Hub
      - name: Push Backend Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-backend:latest

      # Step 10: Push frontend Docker image to Docker Hub
      - name: Push Frontend Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/vite-frontend:latest
